from PyQt5 import QtCore, QtGui, QtWidgets
import pathlib


class Ui_prog2Form(object):
    
    
    assets = pathlib.Path("Assets")
    
    def setupUi(self, prog2Form):
        
        
        prog2Form.setObjectName("prog2Form")
        prog2Form.resize(568, 598)
        
        
        
        self.programming2BG = QtWidgets.QLabel(prog2Form)
        self.programming2BG.setGeometry(QtCore.QRect(0, -40, 831, 741))
        self.programming2BG.setText("")
        self.programming2BG.setPixmap(QtGui.QPixmap(str(self.assets/"label_bg.jpg")))
        self.programming2BG.setObjectName("programming2BG")
        
        
        self.programming2Modal = QtWidgets.QLabel(prog2Form)
        self.programming2Modal.setGeometry(QtCore.QRect(20, 20, 521, 551))
        self.programming2Modal.setStyleSheet("QLabel{ background: #333; border-radius: 10px;}")
        self.programming2Modal.setText("")
        self.programming2Modal.setObjectName("programming2Modal")
        
        
        
        self.labelProgramming2 = QtWidgets.QLabel(prog2Form)
        self.labelProgramming2.setGeometry(QtCore.QRect(170, 40, 251, 61))
        self.labelProgramming2.setStyleSheet("QLabel{font-size: 30px; font-family: century gothic; color: white;}")
        self.labelProgramming2.setObjectName("labelProgramming2")
        
        
        
        self.prog2TextBrowser = QtWidgets.QTextBrowser(prog2Form)
        self.prog2TextBrowser.setGeometry(QtCore.QRect(70, 110, 441, 311))
        self.prog2TextBrowser.setStyleSheet("")
        self.prog2TextBrowser.setObjectName("prog2TextBrowser")
        
        
        
        self.prog2BackButton = QtWidgets.QPushButton(prog2Form)
        self.prog2BackButton.setGeometry(QtCore.QRect(60, 500, 131, 51))
        self.prog2BackButton.setStyleSheet("QPushButton{font-family: century gothic; font-size: 24px;  background: white; color: black; border-radius: 10px;}\n"
"QPushButton:hover{  color: black; background: lightblue;}")
        self.prog2BackButton.setObjectName("prog2BackButton")
        
        
        

        self.retranslateUi(prog2Form)
        QtCore.QMetaObject.connectSlotsByName(prog2Form)




    def retranslateUi(self, prog2Form):
        _translate = QtCore.QCoreApplication.translate
        prog2Form.setWindowTitle(_translate("prog2Form", "Programming 2"))
        self.labelProgramming2.setText(_translate("prog2Form", "PYQT 5 TUTORIAL"))
        self.prog2TextBrowser.setHtml(_translate("prog2Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:600; color:#000000; background-color:#ffffff;\">PyQt - </span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"> is a GUI widgets toolkit. It is a Python interface for </span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000; background-color:#ffffff;\">Qt</span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">, one of the most powerful, and popular cross-platform GUI library.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:600; color:#000000; background-color:#ffffff;\">PyQt API - </span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">is a set of modules containing a large number of classes and functions. While </span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000; background-color:#ffffff;\">QtCore</span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"> module contains non-GUI functionality for working with file and directory etc., </span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000; background-color:#ffffff;\">QtGui</span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"> module contains all the graphical controls. In addition, there are modules for working with XML </span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000; background-color:#ffffff;\">(QtXml)</span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">, SVG </span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000; background-color:#ffffff;\">(QtSvg)</span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">, and SQL </span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000; background-color:#ffffff;\">(QtSql)</span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">, etc.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:600; color:rgba(0,0,0,0.866667);\">Supporting Environments</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:600; color:rgba(0,0,0,0.866667);\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:600; color:#000000; background-color:#ffffff;\">PyQt -</span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"> is compatible with all the popular operating systems including Windows, Linux, and Mac OS. It is dual licensed, available under GPL as well as commercial license.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:600; color:#000000; background-color:#ffffff;\">Major Class in PyQt5 API:</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:600; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtCore</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Core non-GUI classes used by other modules</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtGui</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Graphical user interface components</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtMultimedia</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Classes for low-level multimedia programming</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtNetwork</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Classes for network programming</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtOpenGL</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">OpenGL support classes</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtScript</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Classes for evaluating Qt Scripts</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtSql</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Classes for database integration using SQL</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtSvg</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Classes for displaying the contents of SVG files</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtWebKit</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Classes for rendering and editing HTML</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtXml</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Classes for handling XML</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtAssistant</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Support for online help</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QtDesigner</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Classes for extending Qt Designer</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:600; color:#000000; background-color:#ffffff;\">Commonly used Widgets:</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:600; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QLabel</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Used to display text or image</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QLineEdit</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Allows the user to enter one line of text</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QTextEdit</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Allows the user to enter multi-line text</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QPushButton</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">A command button to invoke action</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QRadioButton</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Enables to choose one from multiple options</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QCheckBox</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Enables choice of more than one options</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QSpinBox</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Enables to increase/decrease an integer value</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QScrollBar</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Enables to access contents of a widget beyond display aperture</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QSlider</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Enables to change the bound value linearly.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QComboBox</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Provides a dropdown list of items to select from</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QMenuBar</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Horizontal bar holding QMenu objects</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QStatusBar</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Usually at bottom of QMainWindow, provides status information.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QToolBar</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Usually at top of QMainWindow or floating. Contains action buttons</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QListView</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Provides a selectable list of items in ListMode or IconMode</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QPixmap</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Off-screen image representation for display on QLabel or QPushButton object.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; font-weight:640; color:#000000;\">QDialog</span></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\">Modal or modeless window which can return information to parent window.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:12pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:8pt; color:#000000; background-color:#ffffff;\">A typical GUI based application’s top level window is created by </span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:8pt; font-weight:640; color:#000000; background-color:#ffffff;\">QMainWindow</span><span style=\" font-family:\'Arial,Verdana,Tahoma\'; font-size:8pt; color:#000000; background-color:#ffffff;\"> widget object. Some widgets as listed above take their appointed place in this main window, while others are placed in the central widget area using various layout managers.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:8pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:8pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:8pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:10px; margin-left:3px; margin-right:3px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:8pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Verdana,Tahoma\'; font-size:8pt; color:#000000;\"><br /></p></body></html>"))
        self.prog2BackButton.setText(_translate("prog2Form", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    prog2Form = QtWidgets.QWidget()
    ui = Ui_prog2Form()
    ui.setupUi(prog2Form)
    prog2Form.show()
    sys.exit(app.exec_())

